---
title: "big function"
author: "Pascal van Luit"
date: "2 February 2020"
output: html_document
---

Arguments;
- baseline.model: the base line which is defined in lavaan syntax.
- min.mi: minimum modification index value for considering a model modification.
- data: dataset on which the model is fit.
- split: percentage of observations placed in the training set.

```{r}
mi_cv <- function(baseline.model, min.mi, data, split){
  # Adding a column to the dataset to allow a train-validation split:
  data <- data %>% 
           mutate(split = rep(c("train", "test"),
                               times = c(round(split * nrow(data)), round((1 - split) * nrow(data)))))
  
  # Making a separate training set:
  train <- data %>%
            filter(split == "train") %>% 
            select(-split)
  
  test <- data %>%
            filter(split == "test") %>% 
            select(-split)
  
  # Fitting the baseline model to the training set:
  fit.train <- lavaan::cfa(baseline.model, train)
  
    # Fitting the baseline model to the test set to obtain a baseline estimate of chi-square model fit:
    fit.test <- lavaan::cfa(baseline.model, test)
    
      #A matrix to store the baseline values of model fit in test set:
      test.baseline.mat <- matrix()
    
      # Obtaining the chi-square value, p-value and degrees of freedom:
      fit.measures.test         <- fitmeasures(fit.test)
      test.baseline.mat$chisq   <- fit.measures.test["chisq"]
      test.baseline.mat$pvalue  <- fit.measures.test["pvalue"]
      test.baseline.mat$df      <- fit.measures.test["df"]
  
  # Obtaining the MIs:
  mi.train <- lavaan::modindices(fit.train)
  
    # Ordering the MIs from largest to smallest:
    mi.train <- mi.train[order(-mi.train$mi), ]
    
    # Taking only the relevant columns:
    mi.train <- mi.train[, 1:4]
    
      # Extracting the first row from those relevant columns:
      lhs <- mi.train[1, 1]
      op  <- mi.train[1, 2]
      rhs <- mi.train[1, 3]
      
    # Adding the first modification to the model:
      ############################
      # No idea how to do this yet..........................
      ############################
      
    # return for checking:
    return(test.baseline.mat)
}
  
```


Testing out function mi_cv:
```{r}
model <- " visual =~ x1 + x2 + x3
           textual =~ x4 + x5 + x6 "

test <- mi_cv(baseline.model = model, data = HolzingerSwineford1939, split = 0.7)

test
```



Things to add:
  - folds
