## mi_cv function
Arguments;
- baseline.model: the baseline sem model which is defined in lavaan syntax.
- min.mi: minimum modification index value for considering a model modification.
- data: dataset on which the model is fit.
- split: percentage of observations placed in the training set.

```{r}
mi_cv <- function(baseline.model, data, split, ...){
  
  # Adding a column to the dataset to allow a train-validation split:
  data <- data %>% 
    mutate(split = rep(c("train", "test"),
                       times = c(round(split * nrow(data)), round((1 - split) * nrow(data)))))
  
  # Making a separate training set:
  train <- data %>%
    filter(split == "train") %>% 
    select(-split)
  
  test <- data %>%
    filter(split == "test") %>% 
    select(-split)
  
  # Saving baseline model as model:
  model <- baseline.model
  
  ## Fitting the baseline model to the training set:
  fit.train <- lavaan::cfa(model, train, ...)
  
  # Obtaining MI values according to the training set:
  MIs <- lavaan::modindices(fit.train)
  
  # Wrangling the MIs:
  MIs <- MIs %>%
    arrange(-mi) %>% 
    select(lhs, op, rhs, mi)
  
  # Specifying a modification to be added to the model:
  mod <- paste(MIs[1, 1], MIs[1, 2], MIs[1, 3], sep = " ")
  
  ## Fitting the baseline model to the test set:
  fit.test.1 <- lavaan::cfa(model, test, ...)
  
  # Creating chisq.diff object: ???????????????????????????????????????????
  sign <- 0
  # chisq.diff <- list(`Pr(>Chisq)` = 0)
  
  ###################
  # WHILE FUNCTTION #
  ###################
  while(sign == 0){
    
    # Extracting a modification to be added to the model:
    mod <- paste(MIs[1, 1], MIs[1, 2], MIs[1, 3], sep = " ")
    
    # Adding modification to the model:
    model <- paste(model, mod, sep = "\n")
    
    # Fitting the model to the test set:
    fit.test.2 <- lavaan::cfa(model, test)
    
    # Checking the chisq.diff in the test set:
    chisq.diff <- lavaan::lavTestLRT(fit.test.1, fit.test.2)
    
    # If function to update sign:
    ifelse(chisq.diff$`Pr(>Chisq)` < .01,
           sign <- 0,
           sign <- 1)
    
    # chisq.diff <- chisq.diff$`Pr(>Chisq)`
    
    # Fitting the model to the train set:
    fit.train <- lavaan::cfa(model, train)
    
    # Obtaining new MI values:
    MIs <- lavaan::modindices(fit.train)
    
    # Wrangling the MIs
    MIs <- MIs %>%
      arrange(-mi) %>% 
      select(lhs, op, rhs, mi)
    
    # Print the final model
    print(model)
    
  }
  
}
```


Testing out function mi_cv:
```{r}
test <- mi_cv(baseline.model = model, data = HolzingerSwineford1939, split = 0.7)

test
```