source("Simulation study/00_create_conditions_grid.R")
source("Simulation study/01_simulation.R")
source("Simulation study/02_Modelling.R")
source("Simulation study/03_Analysis.R")
source("Simulation study/04_Plots.R")