/*in this example, stored locally in folder "ESS" on the C: drive*/
LIBNAME ESS "C:\ESS";
/*To create formats (value labels): edit and run ESSformats program*/
%include "C:\ESS\ESS6e02_4_formats.sas";
run;
data x;
set ESS.ESS6e02_4;
* MS file;
FORMAT
        cntry $CNTRY.
        tvtot TVTOT.
        tvpol TVPOL.
      ppltrst PPLTRST.
      pplfair PPLFAIR.
       pplhlp PPLHLP.
      polintr POLINTR.
      trstprl TRSTPRL.
      trstlgl TRSTLGL.
      trstplc TRSTPLC.
      trstplt TRSTPLT.
      trstprt TRSTPRT.
       trstep TRSTEP.
       trstun TRSTUN.
         vote VOTE.
      prtvtal PRTVTAL.
     prtvtcbe PRTVTCBE.
     prtvtcbg PRTVTCBG.
     prtvtdch PRTVTDCH.
     prtvtacy PRTVTACY.
     prtvtccz PRTVTCCZ.
     prtvdde1 PRTVDDE1F.
     prtvdde2 PRTVDDE2F.
     prtvtcdk PRTVTCDK.
     prtvtdee PRTVTDEE.
     prtvtces PRTVTCES.
     prtvtcfi PRTVTCFI.
     prtvtcfr PRTVTCFR.
      prtvtgb PRTVTGB.
     prtvtdhu PRTVTDHU.
     prtvtaie PRTVTAIE.
     prtvtbil PRTVTBIL.
     prtvtais PRTVTAIS.
     prtvtbit PRTVTBIT.
     prtvalt1 PRTVALT1F.
     prtvalt2 PRTVALT2F.
     prtvalt3 PRTVALT3F.
     prtvtenl PRTVTENL.
     prtvtano PRTVTANO.
     prtvtcpl PRTVTCPL.
     prtvtbpt PRTVTBPT.
     prtvtcru PRTVTCRU.
     prtvtbse PRTVTBSE.
     prtvtdsi PRTVTDSI.
     prtvtcsk PRTVTCSK.
     prtvtcua PRTVTCUA.
      prtvtxk PRTVTXK.
      contplt CONTPLT.
      wrkprty WRKPRTY.
       wrkorg WRKORG.
        badge BADGE.
      sgnptit SGNPTIT.
       pbldmn PBLDMN.
       bctprd BCTPRD.
      clsprty CLSPRTY.
      prtclal PRTCLAL.
     prtclcbe PRTCLCBE.
     prtclcbg PRTCLCBG.
     prtcldch PRTCLDCH.
     prtclacy PRTCLACY.
     prtclccz PRTCLCCZ.
     prtcldde PRTCLDDE.
     prtclcdk PRTCLCDK.
     prtcldee PRTCLDEE.
     prtclces PRTCLCES.
     prtclcfi PRTCLCFI.
     prtcldfr PRTCLDFR.
      prtclgb PRTCLGB.
     prtcldhu PRTCLDHU.
     prtclcie PRTCLCIE.
     prtclcil PRTCLCIL.
     prtclais PRTCLAIS.
     prtclbit PRTCLBIT.
     prtclalt PRTCLALT.
     prtcldnl PRTCLDNL.
     prtclano PRTCLANO.
     prtclepl PRTCLEPL.
     prtclcpt PRTCLCPT.
     prtclcru PRTCLCRU.
     prtclbse PRTCLBSE.
     prtcldsi PRTCLDSI.
     prtclcsk PRTCLCSK.
     prtcldua PRTCLDUA.
      prtclxk PRTCLXK.
      prtdgcl PRTDGCL.
      implvdm IMPLVDM.
      dmcntov DMCNTOV.
      lrscale LRSCALE.
      stflife STFLIFE.
       stfeco STFECO.
       stfgov STFGOV.
       stfdem STFDEM.
       stfedu STFEDU.
      stfhlth STFHLTH.
      gincdif GINCDIF.
      freehms FREEHMS.
        euftf EUFTF.
      imsmetn IMSMETN.
      imdfetn IMDFETN.
      impcntr IMPCNTR.
      imbgeco IMBGECO.
      imueclt IMUECLT.
      imwbcnt IMWBCNT.
        happy HAPPY.
      sclmeet SCLMEET.
      inprdsc INPRDSC.
       sclact SCLACT.
       crmvct CRMVCT.
      aesfdrk AESFDRK.
       health HEALTH.
      hlthhmp HLTHHMP.
       rlgblg RLGBLG.
       rlgdnm RLGDNM.
      rlgdnal RLGDNAL.
      rlgdnbe RLGDNBE.
     rlgdnach RLGDNACH.
      rlgdncy RLGDNCY.
     rlgdnade RLGDNADE.
     rlgdnafi RLGDNAFI.
      rlgdngb RLGDNGB.
      rlgdnhu RLGDNHU.
      rlgdnie RLGDNIE.
      rlgdnil RLGDNIL.
      rlgdnis RLGDNIS.
      rlgdnlt RLGDNLT.
      rlgdnnl RLGDNNL.
      rlgdnno RLGDNNO.
     rlgdnapl RLGDNAPL.
      rlgdnpt RLGDNPT.
     rlgdnaru RLGDNARU.
     rlgdnase RLGDNASE.
      rlgdnsi RLGDNSI.
      rlgdnsk RLGDNSK.
      rlgdnua RLGDNUA.
      rlgblge RLGBLGE.
      rlgdnme RLGDNME.
      rlgdeal RLGDEAL.
      rlgdebe RLGDEBE.
     rlgdeach RLGDEACH.
      rlgdecy RLGDECY.
     rlgdeade RLGDEADE.
     rlgdeafi RLGDEAFI.
      rlgdegb RLGDEGB.
      rlgdehu RLGDEHU.
      rlgdeie RLGDEIE.
      rlgdeil RLGDEIL.
      rlgdeis RLGDEIS.
      rlgdelt RLGDELT.
      rlgdenl RLGDENL.
      rlgdeno RLGDENO.
     rlgdeapl RLGDEAPL.
      rlgdept RLGDEPT.
     rlgdearu RLGDEARU.
     rlgdease RLGDEASE.
      rlgdesi RLGDESI.
      rlgdesk RLGDESK.
      rlgdeua RLGDEUA.
       rlgdgr RLGDGR.
      rlgatnd RLGATND.
         pray PRAY.
      dscrgrp DSCRGRP.
      dscrrce DSCRRCE.
      dscrntn DSCRNTN.
      dscrrlg DSCRRLG.
      dscrlng DSCRLNG.
      dscretn DSCRETN.
      dscrage DSCRAGE.
      dscrgnd DSCRGND.
      dscrsex DSCRSEX.
      dscrdsb DSCRDSB.
      dscroth DSCROTH.
       dscrdk DSCRDK.
      dscrref DSCRREF.
      dscrnap DSCRNAP.
       dscrna DSCRNA.
      ctzcntr CTZCNTR.
     ctzshipc $CTZSHIPC.
      brncntr BRNCNTR.
     cntbrthc $CNTBRTHC.
     livecnta LIVECNTA.
      lnghom1 $LNGHOM1F.
      lnghom2 $LNGHOM2F.
      blgetmg BLGETMG.
       facntr FACNTR.
     fbrncntb $FBRNCNTB.
       mocntr MOCNTR.
     mbrncntb $MBRNCNTB.
      wkvlorg WKVLORG.
       optftr OPTFTR.
       pstvms PSTVMS.
        flrms FLRMS.
       fltdpr FLTDPR.
      flteeff FLTEEFF.
        slprl SLPRL.
        wrhpp WRHPP.
       fltlnl FLTLNL.
        enjlf ENJLF.
        fltsd FLTSD.
       cldgng CLDGNG.
      enrglot ENRGLOT.
       fltanx FLTANX.
      fltpcfl FLTPCFL.
       dclvlf DCLVLF.
      lchshcp LCHSHCP.
       accdng ACCDNG.
      wrbknrm WRBKNRM.
      lrnntlf LRNNTLF.
      pplahlp PPLAHLP.
       trtrsp TRTRSP.
       dngval DNGVAL.
       nhpftr NHPFTR.
      lotsgot LOTSGOT.
        lfwrs LFWRS.
      flclpla FLCLPLA.
      tmdotwa TMDOTWA.
      flapppl FLAPPPL.
      deaimpp DEAIMPP.
      tmimdng TMIMDNG.
      tmabdng TMABDNG.
      tmendng TMENDNG.
      tnapsur TNAPSUR.
      sedirlf SEDIRLF.
      rehlppl REHLPPL.
      prhlppl PRHLPPL.
      plinsoc PLINSOC.
      physact PHYSACT.
      fairelc FAIRELC.
      dspplvt DSPPLVT.
      dfprtal DFPRTAL.
      oppcrgv OPPCRGV.
      medcrgv MEDCRGV.
      meprinf MEPRINF.
      rghmgpr RGHMGPR.
      votedir VOTEDIR.
      imvtctz IMVTCTZ.
      cttresa CTTRESA.
      ctstogv CTSTOGV.
      gptpelc GPTPELC.
      gvctzpv GVCTZPV.
      gvexpdc GVEXPDC.
      grdfinc GRDFINC.
      pltavie PLTAVIE.
     fairelcc FAIRELCC.
     dspplvtc DSPPLVTC.
     dfprtalc DFPRTALC.
     oppcrgvc OPPCRGVC.
     medcrgvc MEDCRGVC.
     meprinfc MEPRINFC.
     rghmgprc RGHMGPRC.
     votedirc VOTEDIRC.
     cttresac CTTRESAC.
     gptpelcc GPTPELCC.
     gvctzpvc GVCTZPVC.
     gvexpdcc GVEXPDCC.
     grdfincc GRDFINCC.
     pltaviec PLTAVIEC.
       fplvdm FPLVDM.
      fplvdmi FPLVDMI.
      fplvdmc FPLVDMC.
      pplvdmi PPLVDMI.
      pplvdmc PPLVDMC.
       chpldm CHPLDM.
      chpldmi CHPLDMI.
      chpldmc CHPLDMC.
      stpldmi STPLDMI.
      stpldmc STPLDMC.
      gvspcdm GVSPCDM.
      gvspdmi GVSPDMI.
      gvspdmc GVSPDMC.
      gvcodmi GVCODMI.
      gvcodmc GVCODMC.
        hhmmb HHMMB.
         gndr GNDR.
        gndr2 GNDR2F.
        gndr3 GNDR3F.
        gndr4 GNDR4F.
        gndr5 GNDR5F.
        gndr6 GNDR6F.
        gndr7 GNDR7F.
        gndr8 GNDR8F.
        gndr9 GNDR9F.
       gndr10 GNDR10F.
       gndr11 GNDR11F.
       gndr12 GNDR12F.
       gndr13 GNDR13F.
       gndr14 GNDR14F.
       gndr15 GNDR15F.
       gndr16 GNDR16F.
       gndr17 GNDR17F.
       gndr18 GNDR18F.
       gndr19 GNDR19F.
       gndr20 GNDR20F.
       gndr21 GNDR21F.
       gndr22 GNDR22F.
       gndr23 GNDR23F.
       gndr24 GNDR24F.
         agea AGEA.
        yrbrn YRBRN.
       yrbrn2 YRBRN2F.
       yrbrn3 YRBRN3F.
       yrbrn4 YRBRN4F.
       yrbrn5 YRBRN5F.
       yrbrn6 YRBRN6F.
       yrbrn7 YRBRN7F.
       yrbrn8 YRBRN8F.
       yrbrn9 YRBRN9F.
      yrbrn10 YRBRN10F.
      yrbrn11 YRBRN11F.
      yrbrn12 YRBRN12F.
      yrbrn13 YRBRN13F.
      yrbrn14 YRBRN14F.
      yrbrn15 YRBRN15F.
      yrbrn16 YRBRN16F.
      yrbrn17 YRBRN17F.
      yrbrn18 YRBRN18F.
      yrbrn19 YRBRN19F.
      yrbrn20 YRBRN20F.
      yrbrn21 YRBRN21F.
      yrbrn22 YRBRN22F.
      yrbrn23 YRBRN23F.
      yrbrn24 YRBRN24F.
      rshipa2 RSHIPA2F.
      rshipa3 RSHIPA3F.
      rshipa4 RSHIPA4F.
      rshipa5 RSHIPA5F.
      rshipa6 RSHIPA6F.
      rshipa7 RSHIPA7F.
      rshipa8 RSHIPA8F.
      rshipa9 RSHIPA9F.
     rshipa10 RSHIPA10F.
     rshipa11 RSHIPA11F.
     rshipa12 RSHIPA12F.
     rshipa13 RSHIPA13F.
     rshipa14 RSHIPA14F.
     rshipa15 RSHIPA15F.
     rshipa16 RSHIPA16F.
     rshipa17 RSHIPA17F.
     rshipa18 RSHIPA18F.
     rshipa19 RSHIPA19F.
     rshipa20 RSHIPA20F.
     rshipa21 RSHIPA21F.
     rshipa22 RSHIPA22F.
     rshipa23 RSHIPA23F.
     rshipa24 RSHIPA24F.
      icpart1 ICPART1F.
      rshpsts RSHPSTS.
      rshpsfi RSHPSFI.
     lvgptnea LVGPTNEA.
     dvrcdeva DVRCDEVA.
      icpart2 ICPART2F.
      iccohbt ICCOHBT.
       marsts MARSTS.
     maritalb MARITALB.
      marstfi MARSTFI.
      marstgb MARSTGB.
      marstie MARSTIE.
       chldhm CHLDHM.
      chldhhe CHLDHHE.
      domicil DOMICIL.
      edulvlb EDULVLB.
       eisced EISCED.
      edlvdal EDLVDAL.
      edlvebe EDLVEBE.
      edlvdbg EDLVDBG.
      edlvdch EDLVDCH.
      edlvecy EDLVECY.
      edlvdcz EDLVDCZ.
      eduade1 EDUADE1F.
       edude2 EDUDE2F.
       edude3 EDUDE3F.
      edlvddk EDLVDDK.
      edlvdee EDLVDEE.
      edlvees EDLVEES.
      edlvdfi EDLVDFI.
      edlvdfr EDLVDFR.
      eduagb1 EDUAGB1F.
       edugb2 EDUGB2F.
      edagegb EDAGEGB.
      edlvdhu EDLVDHU.
      edlvdie EDLVDIE.
      eduail1 EDUAIL1F.
      eduail2 EDUAIL2F.
      edlvdis EDLVDIS.
      edlvdit EDLVDIT.
      edlvdlt EDLVDLT.
      edlvdnl EDLVDNL.
      edlvdno EDLVDNO.
      edlvepl EDLVEPL.
       edupl2 EDUPL2F.
      edlvdpt EDLVDPT.
      edlvdru EDLVDRU.
      edlvdse EDLVDSE.
      edlvdsi EDLVDSI.
      edlvdsk EDLVDSK.
      edlvdua EDLVDUA.
      edlvdxk EDLVDXK.
       eduyrs EDUYRS.
        pdwrk PDWRK.
        edctn EDCTN.
       uempla UEMPLA.
       uempli UEMPLI.
        dsbld DSBLD.
         rtrd RTRD.
        cmsrv CMSRV.
        hswrk HSWRK.
       dngoth DNGOTH.
        dngdk DNGDK.
       dngref DNGREF.
        dngna DNGNA.
      icomdng ICOMDNG.
      mainact MAINACT.
      mnactic MNACTIC.
      icpdwrk ICPDWRK.
       crpdwk CRPDWK.
      pdjobev PDJOBEV.
      pdjobyr PDJOBYR.
      emplrel EMPLREL.
       emplno EMPLNO.
      wrkctra WRKCTRA.
        estsz ESTSZ.
        jbspv JBSPV.
       njbspv NJBSPV.
     wkdcorga WKDCORGA.
      iorgact IORGACT.
        wkhct WKHCT.
       wkhtot WKHTOT.
       nacer2 NACER2F.
      tporgwk TPORGWK.
       isco08 ISCO08F.
      wrkac6m WRKAC6M.
      icpdwk2 ICPDWK2F.
        stfjb STFJB.
      stfjbot STFJBOT.
       uemp3m UEMP3M.
      uemp12m UEMP12M.
      uemp5yr UEMP5YR.
        mbtru MBTRU.
     hincsrca HINCSRCA.
     hinctnta HINCTNTA.
      hincfel HINCFEL.
      icpart3 ICPART3F.
     edulvlpb EDULVLPB.
      eiscedp EISCEDP.
     edlvpdal EDLVPDAL.
     edlvpebe EDLVPEBE.
     edlvpdbg EDLVPDBG.
     edlvpdch EDLVPDCH.
     edlvpecy EDLVPECY.
     edlvpdcz EDLVPDCZ.
     edupade1 EDUPADE1F.
      edupde2 EDUPDE2F.
      edupde3 EDUPDE3F.
     edlvpddk EDLVPDDK.
     edlvpdee EDLVPDEE.
     edlvpees EDLVPEES.
     edlvpdfi EDLVPDFI.
     edlvpdfr EDLVPDFR.
     edupagb1 EDUPAGB1F.
      edupgb2 EDUPGB2F.
     edagepgb EDAGEPGB.
     edlvpdhu EDLVPDHU.
     edlvpdie EDLVPDIE.
     edupail1 EDUPAIL1F.
     edupail2 EDUPAIL2F.
     edlvpdis EDLVPDIS.
     edlvpdit EDLVPDIT.
     edlvpdlt EDLVPDLT.
     edlvpdnl EDLVPDNL.
     edlvpdno EDLVPDNO.
     edlvpepl EDLVPEPL.
      eduppl2 EDUPPL2F.
     edlvpdpt EDLVPDPT.
     edlvpdru EDLVPDRU.
     edlvpdse EDLVPDSE.
     edlvpdsi EDLVPDSI.
     edlvpdsk EDLVPDSK.
     edlvpdua EDLVPDUA.
     edlvpdxk EDLVPDXK.
       pdwrkp PDWRKP.
       edctnp EDCTNP.
      uemplap UEMPLAP.
      uemplip UEMPLIP.
       dsbldp DSBLDP.
        rtrdp RTRDP.
       cmsrvp CMSRVP.
       hswrkp HSWRKP.
      dngothp DNGOTHP.
       dngdkp DNGDKP.
      dngnapp DNGNAPP.
      dngrefp DNGREFP.
       dngnap DNGNAP.
      icomdnp ICOMDNP.
       mnactp MNACTP.
      icppdwk ICPPDWK.
      crpdwkp CRPDWKP.
      isco08p ISCO08P.
      emprelp EMPRELP.
      wkhtotp WKHTOTP.
     edulvlfb EDULVLFB.
      eiscedf EISCEDF.
     edlvfdal EDLVFDAL.
     edlvfebe EDLVFEBE.
     edlvfdbg EDLVFDBG.
     edlvfdch EDLVFDCH.
     edlvfecy EDLVFECY.
     edlvfdcz EDLVFDCZ.
     edufade1 EDUFADE1F.
      edufde2 EDUFDE2F.
      edufde3 EDUFDE3F.
     edlvfddk EDLVFDDK.
     edlvfdee EDLVFDEE.
     edlvfees EDLVFEES.
     edlvfdfi EDLVFDFI.
     edlvfdfr EDLVFDFR.
     edufagb1 EDUFAGB1F.
      edufgb2 EDUFGB2F.
     edagefgb EDAGEFGB.
     edlvfdhu EDLVFDHU.
     edlvfdie EDLVFDIE.
     edufail1 EDUFAIL1F.
     edufail2 EDUFAIL2F.
     edlvfdis EDLVFDIS.
     edlvfdit EDLVFDIT.
     edlvfdlt EDLVFDLT.
     edlvfdnl EDLVFDNL.
     edlvfdno EDLVFDNO.
     edlvfepl EDLVFEPL.
     edlvfdpt EDLVFDPT.
     edlvfdru EDLVFDRU.
     edlvfdse EDLVFDSE.
     edlvfdsi EDLVFDSI.
     edlvfdsk EDLVFDSK.
     edlvfdua EDLVFDUA.
     edlvfdxk EDLVFDXK.
      emprf14 EMPRF14F.
      occf14b OCCF14B.
     edulvlmb EDULVLMB.
      eiscedm EISCEDM.
     edlvmdal EDLVMDAL.
     edlvmebe EDLVMEBE.
     edlvmdbg EDLVMDBG.
     edlvmdch EDLVMDCH.
     edlvmecy EDLVMECY.
     edlvmdcz EDLVMDCZ.
     edumade1 EDUMADE1F.
      edumde2 EDUMDE2F.
      edumde3 EDUMDE3F.
     edlvmddk EDLVMDDK.
     edlvmdee EDLVMDEE.
     edlvmees EDLVMEES.
     edlvmdfi EDLVMDFI.
     edlvmdfr EDLVMDFR.
     edumagb1 EDUMAGB1F.
      edumgb2 EDUMGB2F.
     edagemgb EDAGEMGB.
     edlvmdhu EDLVMDHU.
     edlvmdie EDLVMDIE.
     edumail1 EDUMAIL1F.
     edumail2 EDUMAIL2F.
     edlvmdis EDLVMDIS.
     edlvmdit EDLVMDIT.
     edlvmdlt EDLVMDLT.
     edlvmdnl EDLVMDNL.
     edlvmdno EDLVMDNO.
     edlvmepl EDLVMEPL.
     edlvmdpt EDLVMDPT.
     edlvmdru EDLVMDRU.
     edlvmdse EDLVMDSE.
     edlvmdsi EDLVMDSI.
     edlvmdsk EDLVMDSK.
     edlvmdua EDLVMDUA.
     edlvmdxk EDLVMDXK.
      emprm14 EMPRM14F.
      occm14b OCCM14B.
      atncrse ATNCRSE.
      ipcrtiv IPCRTIV.
      imprich IMPRICH.
      ipeqopt IPEQOPT.
      ipshabt IPSHABT.
      impsafe IMPSAFE.
      impdiff IMPDIFF.
      ipfrule IPFRULE.
      ipudrst IPUDRST.
      ipmodst IPMODST.
      ipgdtim IPGDTIM.
      impfree IMPFREE.
      iphlppl IPHLPPL.
      ipsuces IPSUCES.
      ipstrgv IPSTRGV.
      ipadvnt IPADVNT.
      ipbhprp IPBHPRP.
      iprspot IPRSPOT.
      iplylfr IPLYLFR.
       impenv IMPENV.
      imptrad IMPTRAD.
       impfun IMPFUN.
       region $REGION.
      regunit REGUNIT.
      intewde INTEWDE.
       inwdds INWDDS.
       inwmms INWMMS.
       inwyys INWYYS.
       inwshh INWSHH.
       inwsmm INWSMM.
       inwdde INWDDE.
       inwmme INWMME.
       inwyye INWYYE.
       inwehh INWEHH.
       inwemm INWEMM.
     spltadme SPLTADME.
      supqad1 SUPQAD1F.
      supqad2 SUPQAD2F.
       supqdd SUPQDD.
       supqmm SUPQMM.
       supqyr SUPQYR.

;
/*To create user-defined missing values .a, .b, .c and .d*/
*%include "C:\ESS\ESS_miss.sas";
run;
