```{r}
install.packages("lavaan", dependencies=TRUE)

library(lavaan)

setwd("C:/Users/Gebruiker/Documents/Master/Year 2/Lavaan Tutorial")
```


A First Example: CFA
```{r}
?HolzingerSwineford1939

fit <- cfa(HS.model, data = HolzingerSwineford1939)

summary(fit, fit.measures = TRUE)
```


A Second Example: SEM
```{r}
fit <- sem(model, data = PoliticalDemocracy)
summary(fit, standardized = TRUE)
```


MORE ABOUT THE SYNTAX
```{r}
#Constraining the covariances of the latent variables to be orthogonal
fit.HS.ortho <- cfa(HS.model,
                    data = HolzingerSwineford1939,
                    orthogonal = TRUE)

#Fix the variances of all the latent variables to unity
fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           std.lv = TRUE)#factor loadings of the first indicator of each latent variable no longer fixed to 1.
```

See how the naming mechanism works
```{r}
fit <- sem(model,
           data = PoliticalDemocracy)

coef(fit)
```
 
When you want to add multiple modifiers for the same parameter you must do so seperately - the parser accumulates all the modifiers and treats the parameter as a single indicator.

```{r}
set.seed(1234)
Data <- data.frame(y = rnorm(100),
                   x1 = rnorm(100),
                   x2 = rnorm(100),
                   x3 = rnorm(100))
model <- ' y ~ b1*x1 + b2*x2 + b3*x3 '
fit <- sem(model, data = Data)
coef(fit)
```

Specifying the model with constraints:
```{r}
model.constr <- ' # model with labeled parameters
                    y ~ b1*x1 + b2*x2 + b3*x3
                  # constraints
                    b1 == (b2 + b3)^2
                    b1 > exp(b2 + b3) '
fit <- sem(model.constr, data = Data)
coef(fit)
```


7 BRINGING IN THE MEANS
```{r}
fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           meanstructure = TRUE)
summary(fit)
```


8 MULTIPLE GROUPS
```{r}
fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           group = "school")

summary(fit)
```

```{r}
#Fixed factor loadings included:
fit <- cfa(HS.model,
           data = HolzingerSwineford1939,
           group = "school")

summary(fit)
```










